proxy:
  hide-navbar: true
  landing-page: /
  port: 8080
  template-path: ./
  default-webSocket-reconnection-mode: Auto
  # for cognito authentication: replace {} below and set authentication to openid
  authentication: none
  openid:
    roles-claim: cognito:groups
    auth-url: https://{auth_domain}/oauth2/authorize
    token-url: https://{auth_domain}/oauth2/token
    jwks-url: https://cognito-idp.{region}.amazonaws.com/{user_pool_id}/.well-known/jwks.json
    logout-url: https://{auth_domain}/logout?client_id={client_id}&logout_uri=https://{host_url}
    client-id:
    client-secret:
  # Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: private
    display-name: Dseqr - Private
    description: Your private dseqr workspace
    container-image: alexvpickering/dseqr
    container-cmd: ["Rscript", "run.R", "private", "{host_url}"]
    container-volumes: ["/srv/dseqr:/srv/dseqr"]
    container-network: sp-example-net
    logo-url: https://raw.githubusercontent.com/hms-dbmi/dseqr.sp/master/ninja.svg
  - id: sjiald
    display-name: Dseqr - SJIA-LD
    description: Dseqr application with SJIA-LD data
    container-image: alexvpickering/dseqr
    container-cmd: ["Rscript", "run.R", "sjiald", "{host_url}"]
    container-volumes: ["/srv/dseqr:/srv/dseqr"]
    container-network: sp-example-net
    logo-url: https://raw.githubusercontent.com/hms-dbmi/dseqr.sp/master/ninja.svg
    access-groups: sjiald
  - id: demo
    display-name: Dseqr - Demo
    description: "Read-only Dseqr application to explore demo and reference datasets:"
    container-image: alexvpickering/dseqr
    container-cmd: ["Rscript", "run.R", "example", "{host_url}"]
    container-volumes: ["/srv/dseqr:/srv/dseqr"]
    container-network: sp-example-net
    logo-url: https://raw.githubusercontent.com/hms-dbmi/dseqr.sp/master/favicon.png
logging:
  file:
    shinyproxy.log
server:
    forward-headers-strategy: native # won't redirect to http (need for cognito)
    servlet.session.timeout: 0
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
